

const images ={
    backgroundImage: require('../Assets/Images/background.png'),
    backImage: require('../Assets/Images/back.png'),
    checked: require('../Assets/Images/check.png'),
    uncheck: require('../Assets/Images/uncheck.png'),
    showIcon: require('../Assets/Images/show.png'),
    hideIcon: require('../Assets/Images/hide.png'),
    home: require('../Assets/Images/home.png'),
    homeTabIcon: require('../Assets/Images/campaign_line_tab.png'),
    homeTabIconFilled: require('../Assets/Images/campaign_filled_tab.png'),
    myCompaign: require('../Assets/Images/campaigns.png'),
    myFavorite: require('../Assets/Images/fav.png'),
    setting: require('../Assets/Images/settings.png'),
    aboutKoli: require('../Assets/Images/about.png'),
    privacyPolicy: require('../Assets/Images/Privacy-policy.png'),
    termsCondition: require('../Assets/Images/Privacy-policy.png'),
    faq: require('../Assets/Images/faq.png'),
    help: require('../Assets/Images/help_new.png'),
    logout: require('../Assets/Images/Logout.png'),
    search: require('../Assets/Images/search.png'),
    giveAway: require('../Assets/Images/giveaway-icon.png'),
    logo2: require('../Assets/Images/logo2.png'),
    avtarIcon: require('../Assets/Images/avatar-icon.png'),
    bellIcon: require('../Assets/Images/bell.png'),
    crossRemove: require('../Assets/Images/cross-remove.png'),
    cross: require('../Assets/Images/Group-7106.png'),
    drawerIcon: require('../Assets/Images/Group-6952.png'),
    rightArrowIcon: require('../Assets/Images/next-arrow.png'),
    splash: require('../Assets/Images/splash.png'),
    loaderIcon: require('../Assets/Images/loader.png'),
    tagBlue: require('../Assets/Images/tagBlue.png'),
    tagGreen: require('../Assets/Images/tagGreen.png'),
    tagYellow: require('../Assets/Images/tagYellow.png'),
    timerIcon: require('../Assets/Images/timerIcon.png'),
    rightArrow: require('../Assets/Images/rightArrow.png'),
    jobAwarded: require('../Assets/Images/jobAwarded.png'),
    plusIcon: require('../Assets/Images/plusIcon.png'),
    CalendarIcon: require('../Assets/Images/calc.png'),
    UploadImage: require('../Assets/Images/plusIcon.png'),
    Campaign: require('../Assets/Images/default-campaigns.png'),
    giveAwayIcon: require('../Assets/Images/defaul-giveaway.png'),
    koliIcon: require('../Assets/Images/koli_icon.png'),
    CongratsIcon: require('../Assets/Images/Woohoo.png'),
    ShareIcon : require('../Assets/Images/share.png'),
    MoreIcon : require('../Assets/Images/overflow.png'),
    BackArrow : require('../Assets/Images/back-arrow.png'),
    inactiveRibbon : require('../Assets/Images/inactive.png'),
    cautionIcon : require('../Assets/Images/caution.png'),
    cameraIcon : require('../Assets/Images/ic_photo.png'),
    instaIcon : require('../Assets/Images/Group4253.png'),
    trashIcon : require('../Assets/Images/trash.png'),
    mailIcon : require('../Assets/Images/mail_icon.png'),
    facebookIcon : require('../Assets/Images/facebook.png'),
    insta_Icon : require('../Assets/Images/insta_icon.png'),
    ribbonIcon : require('../Assets/Images/ribbon_blue.png'),
    facebookLogo : require('../Assets/Images/facebookLogo.png'),
    facebookWhiteIcon : require('../Assets/Images/facebook_white.png'),
    editProfileIcon : require('../Assets/Images/account_edit.png'),
    influencerTabLine: require('../Assets/Images/search_line_tab.png'),
    influencerTabFilled: require('../Assets/Images/search_filled_tab.png'),
    campaigTabIcon: require('../Assets/Images/search_line_tab.png'),
    campaigTabIconFilled: require('../Assets/Images/search_filled_tab.png'),
    users: require('../Assets/Images/users.png'),
    SearchResultNo: require('../Assets/Images/no-result.png'),
    CrossSearch: require('../Assets/Images/cross-2.png'),
    Groupgiveaway: require('../Assets/Images/Group.png'),
    AppleIcon: require('../Assets/Images/apple.png'),
    LikeIcon: require('../Assets/Images/Group_6946.png'),
    InstaIcon: require('../Assets/Images/InstaIcon.png'),
    CommentIcon: require('../Assets/Images/Group_6947.png'),
    NoInstagram: require('../Assets/Images/NoInstagram.png'),
    FilterIcon: require('../Assets/Images/filter.png'),
    headerlogo: require('../Assets/Images/headerlogo.png'),
    FilterCross: require('../Assets/Images/FilterCross.png'),
    DropdownIcon: require('../Assets/Images/dropdown.png'),
    headerlogo_ios: require('../Assets/Images/headerlogo_ios.png'),
    chatTabIcon: require('../Assets/Images/Chat-Icon.png'),
    no_notification: require('../Assets/Images/no_notification.png'),
    noChat: require('../Assets/Images/no_chat.png'),
    no_user_info: require('../Assets/Images/no_user_info.png'),
    filter_new: require('../Assets/Images/filter_new.png'),
    sort_new: require('../Assets/Images/sort_new.png'),
    instagram_full: require('../Assets/Images/instagram_full.png'),
    Instastories_bg: require('../Assets/Images/Instastories_bg.png'),
    privateprofile: require('../Assets/Images/privateprofile.png'),
    instaLineIcon : require('../Assets/Images/InstagramLine.png'),
    adminNotification : require('../Assets/Images/adminNotification.png'),
    campaignNotification : require('../Assets/Images/campaignNotification.png'),
    intrestedNotification : require('../Assets/Images/intrestedNotification.png'),
    tick : require('../Assets/Images/tick.png'),
    googleDrive : require('../Assets/Images/GoogleDrive.png'),
    more : require('../Assets/Images/more.png'),
    stripeLogo : require('../Assets/Images/stripeLogo.png'),
    myApplications : require('../Assets/Images/myApplications.png'),
    infoIcon : require('../Assets/Images/infoIcon.png'),
    emptyList : require('../Assets/Images/EmptyList.png'),
    userTabIcon : require('../Assets/Images/user_line_tab.png'),
    userTabFilled : require('../Assets/Images/user_filled_tab.png'),
    chatTabLine : require('../Assets/Images/chat_tab.png'),
    chatTabFilled : require('../Assets/Images/chat_filled_tab.png'),
    PlaceHolder : require('../Assets/Images/placeholder.png'),
    BankInfo : require('../Assets/Images/BankIcon.png'),
    EditIcon : require('../Assets/Images/EditIcon.png'),
    PendingOffer : require('../Assets/Images/PendingOffer.png'),
    RejectedOffer : require('../Assets/Images/CrossInCircle.png'),
    ChatBackground : require('../Assets/Images/ChatBackground.png'),
    ChatSendButton : require('../Assets/Images/ChatSendButton.png'),
    StoreTabLine: require('../Assets/Images/StoreTabLine.png'),
    StoreTabFilled: require('../Assets/Images/StoreTabFilled.png'),
    KoliSquarePlaceholder: require('../Assets/Images/KoliSquarePlaceholder.png'),
    NotificationTabLine: require('../Assets/Images/NotificationTabLine.png'),
    NotificationTabFilled: require('../Assets/Images/NotificationTabFilled.png'),
    HomeTabLine: require('../Assets/Images/HomeTabLine.png'),
    HomeTabFilled: require('../Assets/Images/HomeTabFilled.png'),
    Bullet: require('../Assets/Images/Bullet.png'),
    BlockUser : require('../Assets/Images/block_users.png'),
    Helpdesk : require('../Assets/Images/Helpdesk_icon.png'),
    checktik : require('../Assets/Images/check-tik.png'),
    fbSocial : require('../Assets/Images/fb_icon.png'),
    youtubeSocial : require('../Assets/Images/Youtube_icon.png'),
    tictocSocial : require('../Assets/Images/tictoc_icon.png'),
    twitterSocial : require('../Assets/Images/twitter_icon.png'),
    linkedinSocial : require('../Assets/Images/linkedin.png'),
    clubhouseSocial : require('../Assets/Images/clubhouse_icon.png'),
    livestreamSocial : require('../Assets/Images/livestream.png'),
    twitchSocial : require('../Assets/Images/twitch.png'),
    socialnormal : require('../Assets/Images/socialnormal.png'),
    emailCreateCampaign : require('../Assets/Images/emal_icon.png'),
    socialselect : require('../Assets/Images/socialselect.png'),
    circleCheck : require('../Assets/Images/circle-check.png'),
    shorlisted : require('../Assets/Images/shorlisted.png'),
    search_history : require('../Assets/Images/search_history.png'),

    phone : require('../Assets/Images/phone.png'),
    birthday : require('../Assets/Images/birthday.png'),
    Homepage : require('../Assets/Images/Homepage.png'),
    // shareIcon: require('../Images/share.png'),
    userPlaceholder : require('../Assets/Images/userPlaceholder.png'),

    
    
    

}
export default images