export const MyCompaigns = [
    {
      "ownerId": 521,
      "campaignTitle": "Fdff",
      "campaignImage": "http://koli-media.s3.amazonaws.com/campaigns/15895611325860000.png",
      "campaignGallery": [],
      "campaignDetails": "Dfdsfds",
      "campaignAmount": 55,
      "campaignAmountCurrency": "USD",
      "endStoryPostDate": "2020-05-15T00:00:00.000Z",
      "lookingInfluencerGender": "both",
      "country": "All",
      "countryCode": "NA",
      "shipping": false,
      "productUrl": "Https://google.com",
      "tags": "@aslam",
      "hashtags": "#Fashion",
      "createdAt": "2020-05-14T04:37:28.000Z",
      "updatedAt": "2020-05-18T04:36:35.000Z",
      "isFavourite": false,
      "isFeatured": false,
      "campaignStatus": 1,
      "isDisabled": 0,
      "id": 3
    },
    {
      "ownerId": 521,
      "campaignTitle": "Dfdgf",
      "campaignImage": "http://koli-media.s3.amazonaws.com/campaigns/15895613489320000.png",
      "campaignGallery": [],
      "campaignDetails": "Dfd gd",
      "campaignAmount": 55,
      "campaignAmountCurrency": "USD",
      "endStoryPostDate": "2020-05-15T00:00:00.000Z",
      "lookingInfluencerGender": "both",
      "country": "All",
      "countryCode": "NA",
      "shipping": false,
      "productUrl": "Https://google.com",
      "tags": "@aslam",
      "hashtags": "#Fashion",
      "createdAt": "2020-05-14T04:37:28.000Z",
      "updatedAt": "2020-05-18T06:37:36.000Z",
      "isFavourite": false,
      "isFeatured": false,
      "campaignStatus": 2,
      "isDisabled": 0,
      "id": 5
    },
    {
      "ownerId": 755,
      "campaignTitle": "Arvind is testing jt",
      "campaignImage": "http://koli-media.s3.amazonaws.com/campaigns/15895715574490000.png",
      "campaignGallery": [],
      "campaignDetails": "Yeh haha",
      "campaignAmount": 21,
      "campaignAmountCurrency": "USD",
      "endStoryPostDate": "2020-05-15T00:00:00.000Z",
      "lookingInfluencerGender": "male",
      "country": "All",
      "countryCode": "NA",
      "shipping": true,
      "productUrl": "foo.com",
      "tags": "@arvind21589,Iamsrk",
      "hashtags": "#Fun,#Influencer,#Kaka,#Chacha,#Mama,#Dada,#Chocho,#Melody,#Books,#Evening,#Whatelse,#Itsok,#Nowwhat ,#Space wala,#Kore more,#Letsswwthisone",
      "createdAt": "2020-05-14T04:37:28.000Z",
      "updatedAt": "2020-05-16T12:08:17.000Z",
      "isFavourite": false,
      "isFeatured": false,
      "campaignStatus": 2,
      "isDisabled": 0,
      "id": 8
    },
  ]
